const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  console.log("--- FINAL ALIGNMENT: TEXTICAL BRANCHING CODEX (v13.0) ---");

  const classes = [
    // --- TIER 0 (STARTER) ---
    { id: 1001, name: "Novice", tier: 0, resourceType: "MANA", focus: "Generalist", identity: "A beginner embarking on their journey.", growthDesc: "Slow but steady growth.", mechanicDesc: "Standard Mana.", leadsTo: "23 Foundation Classes", hpGrowth: 5, mpGrowth: 2, atkGrowth: 1, defGrowth: 0.5, spdGrowth: 0.1, promotionReqLevel: 10 },

    // --- TIER 1 (FOUNDATIONS) - 23 Classes ---
    { id: 1101, name: "Squire", tier: 1, resourceType: "MANA", parentClassId: 1001, focus: "Durability", identity: "Defensive starter.", growthDesc: "High HP (+12) and DEF.", mechanicDesc: "+5% Block Chance.", leadsTo: "Knight, Guardian", hpGrowth: 12, mpGrowth: 1, atkGrowth: 1.5, defGrowth: 2.5, spdGrowth: 0.1, promotionReqLevel: 25 },
    { id: 1102, name: "Scout", tier: 1, resourceType: "ENERGY", parentClassId: 1001, focus: "Agility", identity: "Fast exploration.", growthDesc: "High SPD and DEX.", mechanicDesc: "Fast-regen Energy.", leadsTo: "Rogue, Explorer", hpGrowth: 7, mpGrowth: 5, atkGrowth: 2, defGrowth: 0.5, spdGrowth: 0.6, promotionReqLevel: 25 },
    { id: 1103, name: "Apprentice", tier: 1, resourceType: "MANA", parentClassId: 1001, focus: "Magic", identity: "Arcane student.", growthDesc: "High MP and INT.", mechanicDesc: "+5% Mana Regen.", leadsTo: "Wizard, Sorcerer", hpGrowth: 4, mpGrowth: 15, atkGrowth: 0.5, defGrowth: 0.2, spdGrowth: 0.3, promotionReqLevel: 25 },
    { id: 1104, name: "Votary", tier: 1, resourceType: "MANA", parentClassId: 1001, focus: "Resilience", identity: "Survivalist.", growthDesc: "High Regen/Tenacity.", mechanicDesc: "-15% Status Duration.", leadsTo: "Monk, Ascetic", hpGrowth: 10, mpGrowth: 5, atkGrowth: 1, defGrowth: 1, spdGrowth: 0.2, promotionReqLevel: 25 },
    { id: 1105, name: "Brute", tier: 1, resourceType: "RAGE", parentClassId: 1001, focus: "Power", identity: "Pure aggression.", growthDesc: "Massive ATK (+4) and HP.", mechanicDesc: "Uses Rage.", leadsTo: "Berserker, Destroyer", hpGrowth: 15, mpGrowth: 0, atkGrowth: 4, defGrowth: 0.2, spdGrowth: 0.1, promotionReqLevel: 25 },
    { id: 1106, name: "Duelist", tier: 1, resourceType: "ENERGY", parentClassId: 1001, focus: "Precision", identity: "Technical combat.", growthDesc: "High Crit and Acc.", mechanicDesc: "+10% Counter Chance.", leadsTo: "Swordsman, Fencer", hpGrowth: 8, mpGrowth: 2, atkGrowth: 2.5, defGrowth: 1, spdGrowth: 0.4, promotionReqLevel: 25 },
    { id: 1107, name: "Marksman", tier: 1, resourceType: "ENERGY", parentClassId: 1001, focus: "Distance", identity: "Backline damage.", growthDesc: "High Range and Acc.", mechanicDesc: "+1 Base Range.", leadsTo: "Sniper, Hunter", hpGrowth: 6, mpGrowth: 2, atkGrowth: 3, defGrowth: 0.5, spdGrowth: 0.4, promotionReqLevel: 25 },
    { id: 1108, name: "Acolyte", tier: 1, resourceType: "MANA", parentClassId: 1001, focus: "Restoration", identity: "Team healer.", growthDesc: "High MP and HP Regen.", mechanicDesc: "+20% Healing power.", leadsTo: "Priest, Exorcist", hpGrowth: 8, mpGrowth: 10, atkGrowth: 1, defGrowth: 1, spdGrowth: 0.2, promotionReqLevel: 25 },
    { id: 1109, name: "Occultist", tier: 1, resourceType: "MANA", parentClassId: 1001, focus: "Affliction", identity: "Debuff weaver.", growthDesc: "High INT/Debuff.", mechanicDesc: "10% Poison on hit.", leadsTo: "Warlock, Necromancer", hpGrowth: 6, mpGrowth: 12, atkGrowth: 1, defGrowth: 0.5, spdGrowth: 0.3, promotionReqLevel: 25 },
    { id: 1110, name: "Trapper", tier: 1, resourceType: "ENERGY", parentClassId: 1001, focus: "Control", identity: "Grid master.", growthDesc: "High DEX/Trap DMG.", mechanicDesc: "Ignore obstacles.", leadsTo: "Saboteur, Tracker", hpGrowth: 9, mpGrowth: 4, atkGrowth: 2, defGrowth: 1, spdGrowth: 0.5, promotionReqLevel: 25 },
    { id: 1111, name: "Brawler", tier: 1, resourceType: "RAGE", parentClassId: 1001, focus: "Reflexes", identity: "Street fighter.", growthDesc: "High SPD/Dodge.", mechanicDesc: "15% multi-hit chance.", leadsTo: "Champion, Gladiator", hpGrowth: 11, mpGrowth: 0, atkGrowth: 3.5, defGrowth: 0.8, spdGrowth: 0.5, promotionReqLevel: 25 },
    { id: 1112, name: "Mystic", tier: 1, resourceType: "MANA", parentClassId: 1001, focus: "Elemental", identity: "Spirit talker.", growthDesc: "Balanced Magic.", mechanicDesc: "+20% Elem DMG.", leadsTo: "Druid, Elementalist", hpGrowth: 7, mpGrowth: 10, atkGrowth: 1.5, defGrowth: 1, spdGrowth: 0.3, promotionReqLevel: 25 },
    { id: 1113, name: "Taekwondist", tier: 1, resourceType: "RAGE", parentClassId: 1001, focus: "Knockback", identity: "Kicking specialist.", growthDesc: "High Speed (+0.7).", mechanicDesc: "25% Knockback chance.", leadsTo: "Grandmaster, Kick-Master", hpGrowth: 10, mpGrowth: 0, atkGrowth: 3.2, defGrowth: 0.5, spdGrowth: 0.7, promotionReqLevel: 25 },
    { id: 1114, name: "Bard", tier: 1, resourceType: "MANA", parentClassId: 1001, focus: "Auras", identity: "Musical support.", growthDesc: "High MP and Radius.", mechanicDesc: "+10 SPD Aura.", leadsTo: "Troubadour, Minstrel", hpGrowth: 8, mpGrowth: 12, atkGrowth: 1.2, defGrowth: 0.8, spdGrowth: 0.4, promotionReqLevel: 25 },
    { id: 1115, name: "Shaolin", tier: 1, resourceType: "ENERGY", parentClassId: 1001, focus: "Inner Peace", identity: "Flow master.", growthDesc: "High Dodge/Tenacity.", mechanicDesc: "Anti-Stun.", leadsTo: "Zen-Master, Soul-Fist", hpGrowth: 9, mpGrowth: 5, atkGrowth: 2.8, defGrowth: 1.2, spdGrowth: 0.5, promotionReqLevel: 25 },
    { id: 1116, name: "Necrolyte", tier: 1, resourceType: "MANA", parentClassId: 1001, focus: "Life Tap", identity: "Dark student.", growthDesc: "High INT/Lifesteal.", mechanicDesc: "+5 Mana on death.", leadsTo: "Reaper, Soul-Binder", hpGrowth: 7, mpGrowth: 14, atkGrowth: 1.0, defGrowth: 0.4, spdGrowth: 0.3, promotionReqLevel: 25 },
    { id: 1117, name: "Shield-Bearer", tier: 1, resourceType: "RAGE", parentClassId: 1001, focus: "Absolute Guard", identity: "Fortress.", growthDesc: "Highest DEF (+4).", mechanicDesc: "+20% Block Chance.", leadsTo: "Bastion, Fortress", hpGrowth: 14, mpGrowth: 0, atkGrowth: 1.2, defGrowth: 4.0, spdGrowth: 0.05, promotionReqLevel: 25 },
    { id: 1118, name: "Inquisitor", tier: 1, resourceType: "MANA", parentClassId: 1001, focus: "Anti-Magic", identity: "Mage hunter.", growthDesc: "High Magic RES.", mechanicDesc: "+30% DMG vs Mana.", leadsTo: "Templar, Witch-Hunter", hpGrowth: 11, mpGrowth: 5, atkGrowth: 2.5, defGrowth: 1.5, spdGrowth: 0.3, promotionReqLevel: 25 },
    { id: 1119, name: "Dancer", tier: 1, resourceType: "ENERGY", parentClassId: 1001, focus: "Evasion", identity: "Flowing strikes.", growthDesc: "Highest SPD (+0.8).", mechanicDesc: "Dodge bonus on move.", leadsTo: "Blade-Dancer, Mirage-Dancer", hpGrowth: 6, mpGrowth: 4, atkGrowth: 2.0, defGrowth: 0.2, spdGrowth: 0.8, promotionReqLevel: 25 },
    { id: 1120, name: "Wanderer", tier: 1, resourceType: "ENERGY", parentClassId: 1001, focus: "Versatility", identity: "Traveler.", growthDesc: "Balanced (+1.5).", mechanicDesc: "+10% EXP Gain.", leadsTo: "Adventurer, Vagabond", hpGrowth: 10, mpGrowth: 10, atkGrowth: 1.5, defGrowth: 1.5, spdGrowth: 0.4, promotionReqLevel: 25 },
    { id: 1125, name: "Alchemist", tier: 1, resourceType: "MANA", parentClassId: 1001, focus: "Status", identity: "Chemical specialist.", growthDesc: "High INT/Tenacity.", mechanicDesc: "50% stronger items.", leadsTo: "Plague-Doctor, Chemist", hpGrowth: 9, mpGrowth: 12, atkGrowth: 1.5, defGrowth: 1.0, spdGrowth: 0.3, promotionReqLevel: 25 },
    { id: 1126, name: "Ravager", tier: 1, resourceType: "RAGE", parentClassId: 1001, focus: "Adrenaline", identity: "Death-brink warrior.", growthDesc: "Massive ATK.", mechanicDesc: "+ATK per missing HP.", leadsTo: "Reaver, Executioner", hpGrowth: 16, mpGrowth: 0, atkGrowth: 4.5, defGrowth: 0.1, spdGrowth: 0.2, promotionReqLevel: 25 },
    { id: 1130, name: "Crusader", tier: 1, resourceType: "MANA", parentClassId: 1001, focus: "Sanctity", identity: "Holy warrior.", growthDesc: "High HP/RES.", mechanicDesc: "Immune to Poison.", leadsTo: "Paladin, Vindicator", hpGrowth: 13, mpGrowth: 8, atkGrowth: 2.2, defGrowth: 2.2, spdGrowth: 0.2, promotionReqLevel: 25 },

    // --- TIER 2 (SPECIALISTS) ---
    { id: 2101, name: "Knight", tier: 2, resourceType: "RAGE", parentClassId: 1101, focus: "Protection", identity: "Protector.", growthDesc: "High HP/DEF.", mechanicDesc: "Guardian Aura.", leadsTo: "Legend", hpGrowth: 20, mpGrowth: 0, atkGrowth: 3, defGrowth: 4, spdGrowth: 0.2, promotionReqLevel: 50 },
    { id: 2102, name: "Guardian", tier: 2, resourceType: "RAGE", parentClassId: 1101, focus: "Shield Master", identity: "Unbreakable.", growthDesc: "Extreme DEF.", mechanicDesc: "Reflect blocked DMG.", leadsTo: "Legend", hpGrowth: 18, mpGrowth: 0, atkGrowth: 2, defGrowth: 5, spdGrowth: 0.1, promotionReqLevel: 50 },
    { id: 2103, name: "Rogue", tier: 2, resourceType: "ENERGY", parentClassId: 1102, focus: "Stealth", identity: "Unseen killer.", growthDesc: "High SPD/Crit.", mechanicDesc: "+100% Stealth DMG.", leadsTo: "Legend", hpGrowth: 12, mpGrowth: 5, atkGrowth: 4, defGrowth: 1, spdGrowth: 0.8, promotionReqLevel: 50 },
    { id: 2104, name: "Explorer", tier: 2, resourceType: "ENERGY", parentClassId: 1102, focus: "Mobility", identity: "Traveler.", growthDesc: "Highest SPD.", mechanicDesc: "+2 Move Range.", leadsTo: "Legend", hpGrowth: 14, mpGrowth: 10, atkGrowth: 3, defGrowth: 1.5, spdGrowth: 1.2, promotionReqLevel: 50 },
    { id: 2105, name: "Wizard", tier: 2, resourceType: "MANA", parentClassId: 1103, focus: "AOE", identity: "Mass magic.", growthDesc: "Extreme INT.", mechanicDesc: "Larger AOE.", leadsTo: "Legend", hpGrowth: 8, mpGrowth: 25, atkGrowth: 1, defGrowth: 0.5, spdGrowth: 0.4, promotionReqLevel: 50 },
    { id: 2106, name: "Sorcerer", tier: 2, resourceType: "MANA", parentClassId: 1103, focus: "Burst", identity: "Single target.", growthDesc: "Highest INT.", mechanicDesc: "Spell Crit.", leadsTo: "Legend", hpGrowth: 7, mpGrowth: 20, atkGrowth: 1, defGrowth: 0.5, spdGrowth: 0.5, promotionReqLevel: 50 },
    { id: 2107, name: "Monk", tier: 2, resourceType: "ENERGY", parentClassId: 1104, focus: "Harmony", identity: "Spiritual.", growthDesc: "High Tenacity.", mechanicDesc: "Mana Shield.", leadsTo: "Legend", hpGrowth: 18, mpGrowth: 15, atkGrowth: 3.5, defGrowth: 2.5, spdGrowth: 0.5, promotionReqLevel: 50 },
    { id: 2108, name: "Ascetic", tier: 2, resourceType: "MANA", parentClassId: 1104, focus: "Resilience", identity: "Unshakeable.", growthDesc: "Extreme Tenacity.", mechanicDesc: "DOT Immunity.", leadsTo: "Legend", hpGrowth: 22, mpGrowth: 10, atkGrowth: 2, defGrowth: 3, spdGrowth: 0.3, promotionReqLevel: 50 },
    { id: 2109, name: "Berserker", tier: 2, resourceType: "RAGE", parentClassId: 1105, focus: "Rage", identity: "Pain master.", growthDesc: "Massive ATK.", mechanicDesc: "Low HP Bonus.", leadsTo: "Legend", hpGrowth: 20, mpGrowth: 0, atkGrowth: 6, defGrowth: 0.5, spdGrowth: 0.3, promotionReqLevel: 50 },
    { id: 2110, name: "Destroyer", tier: 2, resourceType: "RAGE", parentClassId: 1105, focus: "Impact", identity: "Siege master.", growthDesc: "High ATK.", mechanicDesc: "Ignore 30% DEF.", leadsTo: "Legend", hpGrowth: 25, mpGrowth: 0, atkGrowth: 5, defGrowth: 1, spdGrowth: 0.2, promotionReqLevel: 50 },
    { id: 2111, name: "Swordsman", tier: 2, resourceType: "ENERGY", parentClassId: 1106, focus: "Technique", identity: "Finesse.", growthDesc: "High Crit.", mechanicDesc: "+20% Crit DMG.", leadsTo: "Legend", hpGrowth: 15, mpGrowth: 5, atkGrowth: 4.5, defGrowth: 2, spdGrowth: 0.5, promotionReqLevel: 50 },
    { id: 2112, name: "Fencer", tier: 2, resourceType: "ENERGY", parentClassId: 1106, focus: "Parry", identity: "Untouchable.", growthDesc: "High Dodge.", mechanicDesc: "+15% Parry.", leadsTo: "Legend", hpGrowth: 12, mpGrowth: 5, atkGrowth: 3.5, defGrowth: 1, spdGrowth: 0.9, promotionReqLevel: 50 },
    { id: 2113, name: "Sniper", tier: 2, resourceType: "ENERGY", parentClassId: 1107, focus: "Range", identity: "Extreme reach.", growthDesc: "Highest Range.", mechanicDesc: "+2 Range; Static Shot.", leadsTo: "Legend", hpGrowth: 10, mpGrowth: 5, atkGrowth: 5, defGrowth: 0.5, spdGrowth: 0.4, promotionReqLevel: 50 },
    { id: 2114, name: "Hunter", tier: 2, resourceType: "ENERGY", parentClassId: 1107, focus: "Trapper", identity: "Wilderness.", growthDesc: "Balanced.", mechanicDesc: "Beast Bane.", leadsTo: "Legend", hpGrowth: 14, mpGrowth: 8, atkGrowth: 4, defGrowth: 1.5, spdGrowth: 0.6, promotionReqLevel: 50 },
    { id: 2115, name: "Priest", tier: 2, resourceType: "MANA", parentClassId: 1108, focus: "Healing", identity: "Beacon.", growthDesc: "Regen.", mechanicDesc: "Purify Heals.", leadsTo: "Legend", hpGrowth: 14, mpGrowth: 20, atkGrowth: 1.5, defGrowth: 2, spdGrowth: 0.3, promotionReqLevel: 50 },
    { id: 2116, name: "Exorcist", tier: 2, resourceType: "MANA", parentClassId: 1108, focus: "Holy DMG", identity: "Evil's bane.", growthDesc: "High INT.", mechanicDesc: "+50% DMG vs Undead.", leadsTo: "Legend", hpGrowth: 16, mpGrowth: 15, atkGrowth: 3, defGrowth: 2, spdGrowth: 0.4, promotionReqLevel: 50 },
    { id: 2117, name: "Warlock", tier: 2, resourceType: "MANA", parentClassId: 1109, focus: "Debuffs", identity: "Curse weaver.", growthDesc: "High INT.", mechanicDesc: "Debuff Synergy.", leadsTo: "Legend", hpGrowth: 10, mpGrowth: 20, atkGrowth: 2, defGrowth: 1, spdGrowth: 0.4, promotionReqLevel: 50 },
    { id: 2118, name: "Necromancer", tier: 2, resourceType: "MANA", parentClassId: 1109, focus: "Minions", identity: "Dead-speaker.", growthDesc: "High INT.", mechanicDesc: "Summon Skeleton.", leadsTo: "Legend", hpGrowth: 12, mpGrowth: 25, atkGrowth: 1.5, defGrowth: 1, spdGrowth: 0.3, promotionReqLevel: 50 },
    { id: 2119, name: "Saboteur", tier: 2, resourceType: "ENERGY", parentClassId: 1110, focus: "Explosives", identity: "Bomb master.", growthDesc: "High DEX.", mechanicDesc: "Place Traps.", leadsTo: "Legend", hpGrowth: 13, mpGrowth: 6, atkGrowth: 3.5, defGrowth: 2, spdGrowth: 0.6, promotionReqLevel: 50 },
    { id: 2120, name: "Tracker", tier: 2, resourceType: "ENERGY", parentClassId: 1110, focus: "Spotting", identity: "Intelligence.", growthDesc: "High DEX.", mechanicDesc: "True Sight.", leadsTo: "Legend", hpGrowth: 15, mpGrowth: 10, atkGrowth: 2.5, defGrowth: 2, spdGrowth: 0.8, promotionReqLevel: 50 },
    { id: 2121, name: "Champion", tier: 2, resourceType: "RAGE", parentClassId: 1111, focus: "Combo", identity: "Strike master.", growthDesc: "High SPD.", mechanicDesc: "Triple Strike.", leadsTo: "Legend", hpGrowth: 16, mpGrowth: 0, atkGrowth: 5, defGrowth: 1.5, spdGrowth: 0.5, promotionReqLevel: 50 },
    { id: 2122, name: "Gladiator", tier: 2, resourceType: "RAGE", parentClassId: 1111, focus: "Control", identity: "Arena king.", growthDesc: "High HP.", mechanicDesc: "Chance to Stun.", leadsTo: "Legend", hpGrowth: 20, mpGrowth: 0, atkGrowth: 4.5, defGrowth: 2, spdGrowth: 0.4, promotionReqLevel: 50 },
    { id: 2123, name: "Druid", tier: 2, resourceType: "MANA", parentClassId: 1112, focus: "Terrain", identity: "Grove keeper.", growthDesc: "High MP.", mechanicDesc: "Tile Transform.", leadsTo: "Legend", hpGrowth: 12, mpGrowth: 18, atkGrowth: 2.5, defGrowth: 2, spdGrowth: 0.4, promotionReqLevel: 50 },
    { id: 2124, name: "Elementalist", tier: 2, resourceType: "MANA", parentClassId: 1112, focus: "Elements", identity: "Force master.", growthDesc: "High INT.", mechanicDesc: "Element Swap.", leadsTo: "Legend", hpGrowth: 10, mpGrowth: 22, atkGrowth: 2, defGrowth: 1, spdGrowth: 0.5, promotionReqLevel: 50 },
    { id: 2125, name: "Grandmaster", tier: 2, resourceType: "ENERGY", parentClassId: 1113, focus: "Momentum", identity: "Speed fighter.", growthDesc: "Highest SPD.", mechanicDesc: "Move-to-Power.", leadsTo: "Legend", hpGrowth: 14, mpGrowth: 5, atkGrowth: 4.5, defGrowth: 1, spdGrowth: 1.0, promotionReqLevel: 50 },
    { id: 2126, name: "Kick-Master", tier: 2, resourceType: "RAGE", parentClassId: 1113, focus: "Displacement", identity: "Heavy kicker.", growthDesc: "High ATK.", mechanicDesc: "AoE Knockback.", leadsTo: "Legend", hpGrowth: 16, mpGrowth: 0, atkGrowth: 5, defGrowth: 1, spdGrowth: 0.8, promotionReqLevel: 50 },
    { id: 2127, name: "Troubadour", tier: 2, resourceType: "MANA", parentClassId: 1114, focus: "Global Buff", identity: "Singer.", growthDesc: "Highest MP.", mechanicDesc: "Global Auras.", leadsTo: "Legend", hpGrowth: 12, mpGrowth: 30, atkGrowth: 1.5, defGrowth: 1.5, spdGrowth: 0.5, promotionReqLevel: 50 },
    { id: 2128, name: "Minstrel", tier: 2, resourceType: "MANA", parentClassId: 1114, focus: "Debuffs", identity: "Chaos singer.", growthDesc: "High INT.", mechanicDesc: "Global Debuff.", leadsTo: "Legend", hpGrowth: 14, mpGrowth: 25, atkGrowth: 2, defGrowth: 1, spdGrowth: 0.6, promotionReqLevel: 50 },
    { id: 2129, name: "Zen-Master", tier: 2, resourceType: "ENERGY", parentClassId: 1115, focus: "Evasion", identity: "Untouchable.", growthDesc: "Highest Dodge.", mechanicDesc: "Dodge to Speed.", leadsTo: "Legend", hpGrowth: 12, mpGrowth: 10, atkGrowth: 3, defGrowth: 1, spdGrowth: 0.9, promotionReqLevel: 50 },
    { id: 2130, name: "Soul-Fist", tier: 2, resourceType: "ENERGY", parentClassId: 1115, focus: "Internal DMG", identity: "Vitality burner.", growthDesc: "High ATK.", mechanicDesc: "Ignore Block.", leadsTo: "Legend", hpGrowth: 15, mpGrowth: 10, atkGrowth: 5, defGrowth: 2, spdGrowth: 0.6, promotionReqLevel: 50 },
    { id: 2131, name: "Reaper", tier: 2, resourceType: "MANA", parentClassId: 1116, focus: "Harvest", identity: "Soul collector.", growthDesc: "High ATK/Lifesteal.", mechanicDesc: "Life Leech.", leadsTo: "Legend", hpGrowth: 14, mpGrowth: 15, atkGrowth: 5, defGrowth: 1, spdGrowth: 0.4, promotionReqLevel: 50 },
    { id: 2132, name: "Soul-Binder", tier: 2, resourceType: "MANA", parentClassId: 1116, focus: "Control", identity: "Manipulator.", growthDesc: "High INT.", mechanicDesc: "Redirect Healing.", leadsTo: "Legend", hpGrowth: 12, mpGrowth: 20, atkGrowth: 2, defGrowth: 1.5, spdGrowth: 0.3, promotionReqLevel: 50 },
    { id: 2133, name: "Bastion", tier: 2, resourceType: "RAGE", parentClassId: 1117, focus: "Immovable", identity: "Living wall.", growthDesc: "Highest DEF.", mechanicDesc: "No knockback.", leadsTo: "Legend", hpGrowth: 22, mpGrowth: 0, atkGrowth: 2, defGrowth: 6, spdGrowth: 0.1, promotionReqLevel: 50 },
    { id: 2134, name: "Fortress", tier: 2, resourceType: "RAGE", parentClassId: 1117, focus: "Static Guard", identity: "Ultimate bunker.", growthDesc: "High HP/DEF.", mechanicDesc: "+30 DEF Aura.", leadsTo: "Legend", hpGrowth: 25, mpGrowth: 0, atkGrowth: 1.5, defGrowth: 5.5, spdGrowth: 0.05, promotionReqLevel: 50 },
    { id: 2135, name: "Templar", tier: 2, resourceType: "MANA", parentClassId: 1118, focus: "Holy Smite", identity: "Divine knight.", growthDesc: "High ATK.", mechanicDesc: "Holy Damage.", leadsTo: "Legend", hpGrowth: 18, mpGrowth: 10, atkGrowth: 4.5, defGrowth: 3, spdGrowth: 0.3, promotionReqLevel: 50 },
    { id: 2136, name: "Witch-Hunter", tier: 2, resourceType: "MANA", parentClassId: 1118, focus: "Silence", identity: "Arcane bane.", growthDesc: "High Magic RES.", mechanicDesc: "Silence on Hit.", leadsTo: "Legend", hpGrowth: 16, mpGrowth: 12, atkGrowth: 4, defGrowth: 2, spdGrowth: 0.5, promotionReqLevel: 50 },
    { id: 2137, name: "Blade-Dancer", tier: 2, resourceType: "ENERGY", parentClassId: 1119, focus: "Offense", identity: "Killer.", growthDesc: "High SPD/ATK.", mechanicDesc: "Post-Dodge hit.", leadsTo: "Legend", hpGrowth: 12, mpGrowth: 5, atkGrowth: 5, defGrowth: 0.5, spdGrowth: 1.0, promotionReqLevel: 50 },
    { id: 2138, name: "Mirage-Dancer", tier: 2, resourceType: "ENERGY", parentClassId: 1119, focus: "Evasion", identity: "Ghost walker.", growthDesc: "Highest Dodge.", mechanicDesc: "Confuse enemies.", leadsTo: "Legend", hpGrowth: 10, mpGrowth: 8, atkGrowth: 3, defGrowth: 0.5, spdGrowth: 1.2, promotionReqLevel: 50 },
    { id: 2139, name: "Adventurer", tier: 2, resourceType: "ENERGY", parentClassId: 1120, focus: "Generalist", identity: "True hero.", growthDesc: "Balanced.", mechanicDesc: "Equip anything.", leadsTo: "Legend", hpGrowth: 15, mpGrowth: 15, atkGrowth: 2.5, defGrowth: 2.5, spdGrowth: 0.6, promotionReqLevel: 50 },
    { id: 2140, name: "Vagabond", tier: 2, resourceType: "ENERGY", parentClassId: 1120, focus: "Survival", identity: "Luck master.", growthDesc: "High Luck/SPD.", mechanicDesc: "Cheat Death.", leadsTo: "Legend", hpGrowth: 18, mpGrowth: 5, atkGrowth: 3.5, defGrowth: 1.5, spdGrowth: 0.7, promotionReqLevel: 50 },
    { id: 2141, name: "Plague-Doctor", tier: 2, resourceType: "MANA", parentClassId: 1125, focus: "Toxins", identity: "Disease expert.", growthDesc: "High Tenacity.", mechanicDesc: "Extended DOTs.", leadsTo: "Legend", hpGrowth: 14, mpGrowth: 15, atkGrowth: 2, defGrowth: 2, spdGrowth: 0.4, promotionReqLevel: 50 },
    { id: 2142, name: "Chemist", tier: 2, resourceType: "ENERGY", parentClassId: 1125, focus: "Support", identity: "Concocter.", growthDesc: "High SPD.", mechanicDesc: "Double Item Use.", leadsTo: "Legend", hpGrowth: 12, mpGrowth: 12, atkGrowth: 2.5, defGrowth: 1.5, spdGrowth: 0.6, promotionReqLevel: 50 },
    { id: 2143, name: "Reaver", tier: 2, resourceType: "RAGE", parentClassId: 1126, focus: "Drain", identity: "Blood sucker.", growthDesc: "High ATK.", mechanicDesc: "Life Leech.", leadsTo: "Legend", hpGrowth: 18, mpGrowth: 0, atkGrowth: 5.5, defGrowth: 1, spdGrowth: 0.4, promotionReqLevel: 50 },
    { id: 2144, name: "Executioner", tier: 2, resourceType: "RAGE", parentClassId: 1126, focus: "Finisher", identity: "Merciless.", growthDesc: "Highest ATK.", mechanicDesc: "Low HP Insta-kill.", leadsTo: "Legend", hpGrowth: 16, mpGrowth: 0, atkGrowth: 7.0, defGrowth: 0.5, spdGrowth: 0.3, promotionReqLevel: 50 },
    { id: 2145, name: "Paladin", tier: 2, resourceType: "MANA", parentClassId: 1130, focus: "Holy Tank", identity: "Divine shield.", growthDesc: "High DEF/RES.", mechanicDesc: "Heal on block.", leadsTo: "Legend", hpGrowth: 18, mpGrowth: 10, atkGrowth: 2.5, defGrowth: 3, spdGrowth: 0.2, promotionReqLevel: 50 },
    { id: 2146, name: "Vindicator", tier: 2, resourceType: "MANA", parentClassId: 1130, focus: "Aggression", identity: "Holy judge.", growthDesc: "High ATK.", mechanicDesc: "+20% Holy DMG.", leadsTo: "Legend", hpGrowth: 16, mpGrowth: 12, atkGrowth: 5.0, defGrowth: 2, spdGrowth: 0.4, promotionReqLevel: 50 }
  ];

  for (const c of classes) {
    await prisma.classTemplate.upsert({
      where: { id: c.id },
      update: c,
      create: c
    });
  }

  console.log("✅ Textical Branching Codex v13.0 Seeded.");
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
