const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  console.log("--- SEEDING TEXTICAL SPECIALIST CODEX (v11.0 - TIER 2 EVOLUTION) ---");

  const classes = [
    // --- TIER 0 (STARTER) ---
    { id: 1001, name: "Novice", tier: 0, resourceType: "MANA", focus: "Generalist", identity: "A beginner embarking on their journey.", growthDesc: "Slow but steady growth.", mechanicDesc: "Standard Mana.", leadsTo: "All Tier 1", hpGrowth: 5, mpGrowth: 2, atkGrowth: 1, defGrowth: 0.5, spdGrowth: 0.1, promotionReqLevel: 10 },

    // --- TIER 1 (FOUNDATIONS) ---
    { id: 1101, name: "Squire", tier: 1, resourceType: "MANA", parentClassId: 1001, focus: "Durability", identity: "Defensive starter.", growthDesc: "High HP (+12) and DEF (+2.5).", mechanicDesc: "+5% Block Chance.", leadsTo: "Knight", hpGrowth: 12, mpGrowth: 1, atkGrowth: 1.5, defGrowth: 2.5, spdGrowth: 0.1, promotionReqLevel: 25 },
    { id: 1102, name: "Scout", tier: 1, resourceType: "ENERGY", parentClassId: 1001, focus: "Agility", identity: "Fast exploration.", growthDesc: "High SPD (+0.6) and DEX.", mechanicDesc: "Fast-regen Energy.", leadsTo: "Rogue", hpGrowth: 7, mpGrowth: 5, atkGrowth: 2, defGrowth: 0.5, spdGrowth: 0.6, promotionReqLevel: 25 },
    { id: 1103, name: "Apprentice", tier: 1, resourceType: "MANA", parentClassId: 1001, focus: "Magic", identity: "Arcane student.", growthDesc: "High MP (+15) and INT.", mechanicDesc: "+5% Mana Regen.", leadsTo: "Wizard", hpGrowth: 4, mpGrowth: 15, atkGrowth: 0.5, defGrowth: 0.2, spdGrowth: 0.3, promotionReqLevel: 25 },
    { id: 1104, name: "Votary", tier: 1, resourceType: "MANA", parentClassId: 1001, focus: "Resilience", identity: "Survivalist.", growthDesc: "High HP Regen and Tenacity.", mechanicDesc: "-15% Status Durations.", leadsTo: "Monk", hpGrowth: 10, mpGrowth: 5, atkGrowth: 1, defGrowth: 1, spdGrowth: 0.2, promotionReqLevel: 25 },
    { id: 1105, name: "Brute", tier: 1, resourceType: "RAGE", parentClassId: 1001, focus: "Power", identity: "Pure aggression.", growthDesc: "Massive ATK (+4) and HP (+15).", mechanicDesc: "Uses Rage.", leadsTo: "Berserker", hpGrowth: 15, mpGrowth: 0, atkGrowth: 4, defGrowth: 0.2, spdGrowth: 0.1, promotionReqLevel: 25 },
    { id: 1106, name: "Duelist", tier: 1, resourceType: "ENERGY", parentClassId: 1001, focus: "Precision", identity: "Technical combat.", growthDesc: "High Crit and Accuracy.", mechanicDesc: "+10% Counter Chance.", leadsTo: "Swordsman, Fencer", hpGrowth: 8, mpGrowth: 2, atkGrowth: 2.5, defGrowth: 1, spdGrowth: 0.4, promotionReqLevel: 25 },
    { id: 1107, name: "Marksman", tier: 1, resourceType: "ENERGY", parentClassId: 1001, focus: "Distance", identity: "Backline damage.", growthDesc: "High Range and Acc.", mechanicDesc: "+1 Base Range.", leadsTo: "Sniper", hpGrowth: 6, mpGrowth: 2, atkGrowth: 3, defGrowth: 0.5, spdGrowth: 0.4, promotionReqLevel: 25 },
    { id: 1108, name: "Acolyte", tier: 1, resourceType: "MANA", parentClassId: 1001, focus: "Restoration", identity: "Team healer.", growthDesc: "High MP and HP Regen.", mechanicDesc: "+20% Healing power.", leadsTo: "Priest", hpGrowth: 8, mpGrowth: 10, atkGrowth: 1, defGrowth: 1, spdGrowth: 0.2, promotionReqLevel: 25 },
    { id: 1109, name: "Occultist", tier: 1, resourceType: "MANA", parentClassId: 1001, focus: "Affliction", identity: "Debuff weaver.", growthDesc: "High INT and Debuff Success.", mechanicDesc: "10% Poison chance on hit.", leadsTo: "Warlock", hpGrowth: 6, mpGrowth: 12, atkGrowth: 1, defGrowth: 0.5, spdGrowth: 0.3, promotionReqLevel: 25 },
    { id: 1110, name: "Trapper", tier: 1, resourceType: "ENERGY", parentClassId: 1001, focus: "Control", identity: "Grid master.", growthDesc: "High DEX and Trap DMG.", mechanicDesc: "Ignore minor obstacles.", leadsTo: "Saboteur", hpGrowth: 9, mpGrowth: 4, atkGrowth: 2, defGrowth: 1, spdGrowth: 0.5, promotionReqLevel: 25 },
    { id: 1111, name: "Brawler", tier: 1, resourceType: "RAGE", parentClassId: 1001, focus: "Reflexes", identity: "Street fighter.", growthDesc: "High SPD and Dodge.", mechanicDesc: "15% chance to multi-hit.", leadsTo: "Champion", hpGrowth: 11, mpGrowth: 0, atkGrowth: 3.5, defGrowth: 0.8, spdGrowth: 0.5, promotionReqLevel: 25 },
    { id: 1112, name: "Mystic", tier: 1, resourceType: "MANA", parentClassId: 1001, focus: "Elemental", identity: "Spirit talker.", growthDesc: "Balanced Magic.", mechanicDesc: "+20% Elemental DMG.", leadsTo: "Druid", hpGrowth: 7, mpGrowth: 10, atkGrowth: 1.5, defGrowth: 1, spdGrowth: 0.3, promotionReqLevel: 25 },
    { id: 1113, name: "Taekwondist", tier: 1, resourceType: "RAGE", parentClassId: 1001, focus: "Knockback", identity: "Kicking specialist.", growthDesc: "High SPD (+0.7).", mechanicDesc: "25% Knockback chance.", leadsTo: "Grandmaster", hpGrowth: 10, mpGrowth: 0, atkGrowth: 3.2, defGrowth: 0.5, spdGrowth: 0.7, promotionReqLevel: 25 },
    { id: 1114, name: "Bard", tier: 1, resourceType: "MANA", parentClassId: 1001, focus: "Auras", identity: "Musical support.", growthDesc: "High MP and Radius.", mechanicDesc: "+10 SPD Aura for allies.", leadsTo: "Troubadour", hpGrowth: 8, mpGrowth: 12, atkGrowth: 1.2, defGrowth: 0.8, spdGrowth: 0.4, promotionReqLevel: 25 },
    { id: 1115, name: "Shaolin", tier: 1, resourceType: "ENERGY", parentClassId: 1001, focus: "Inner Peace", identity: "Flow master.", growthDesc: "High Dodge and Tenacity.", mechanicDesc: "Anti-Stun while healthy.", leadsTo: "Zen-Master", hpGrowth: 9, mpGrowth: 5, atkGrowth: 2.8, defGrowth: 1.2, spdGrowth: 0.5, promotionReqLevel: 25 },
    { id: 1116, name: "Necrolyte", tier: 1, resourceType: "MANA", parentClassId: 1001, focus: "Life Tap", identity: "Forbidden student.", growthDesc: "High INT and Lifesteal.", mechanicDesc: "+5 Mana on enemy death.", leadsTo: "Reaper", hpGrowth: 7, mpGrowth: 14, atkGrowth: 1.0, defGrowth: 0.4, spdGrowth: 0.3, promotionReqLevel: 25 },
    { id: 1117, name: "Shield-Bearer", tier: 1, resourceType: "RAGE", parentClassId: 1001, focus: "Absolute Guard", identity: "Walking fortress.", growthDesc: "Highest DEF (+4).", mechanicDesc: "+20% Block Chance.", leadsTo: "Bastion", hpGrowth: 14, mpGrowth: 0, atkGrowth: 1.2, defGrowth: 4.0, spdGrowth: 0.05, promotionReqLevel: 25 },
    { id: 1118, name: "Inquisitor", tier: 1, resourceType: "MANA", parentClassId: 1001, focus: "Anti-Magic", identity: "Mage hunter.", growthDesc: "High Magic RES.", mechanicDesc: "+30% DMG vs Mana users.", leadsTo: "Templar", hpGrowth: 11, mpGrowth: 5, atkGrowth: 2.5, defGrowth: 1.5, spdGrowth: 0.3, promotionReqLevel: 25 },
    { id: 1119, name: "Dancer", tier: 1, resourceType: "ENERGY", parentClassId: 1001, focus: "Evasion", identity: "Flowing strikes.", growthDesc: "Highest SPD (+0.8).", mechanicDesc: "Dodge bonus per tile moved.", leadsTo: "Blade-Dancer", hpGrowth: 6, mpGrowth: 4, atkGrowth: 2.0, defGrowth: 0.2, spdGrowth: 0.8, promotionReqLevel: 25 },
    { id: 1120, name: "Wanderer", tier: 1, resourceType: "ENERGY", parentClassId: 1001, focus: "Versatility", identity: "World traveler.", growthDesc: "Balanced stats.", mechanicDesc: "+10% EXP Gain.", leadsTo: "Adventurer", hpGrowth: 10, mpGrowth: 10, atkGrowth: 1.5, defGrowth: 1.5, spdGrowth: 0.4, promotionReqLevel: 25 },
    { id: 1125, name: "Alchemist", tier: 1, resourceType: "MANA", parentClassId: 1001, focus: "Status", identity: "Chemical specialist.", growthDesc: "High INT and Tenacity.", mechanicDesc: "50% stronger items.", leadsTo: "Plague-Doctor", hpGrowth: 9, mpGrowth: 12, atkGrowth: 1.5, defGrowth: 1.0, spdGrowth: 0.3, promotionReqLevel: 25 },
    { id: 1126, name: "Ravager", tier: 1, resourceType: "RAGE", parentClassId: 1001, focus: "Adrenaline", identity: "Death-brink warrior.", growthDesc: "Massive ATK.", mechanicDesc: "+ATK per missing HP.", leadsTo: "Reaver", hpGrowth: 16, mpGrowth: 0, atkGrowth: 4.5, defGrowth: 0.1, spdGrowth: 0.2, promotionReqLevel: 25 },
    { id: 1130, name: "Crusader", tier: 1, resourceType: "MANA", parentClassId: 1001, focus: "Sanctity", identity: "Holy warrior.", growthDesc: "High HP and RES.", mechanicDesc: "Immune to Poison.", leadsTo: "Paladin", hpGrowth: 13, mpGrowth: 8, atkGrowth: 2.2, defGrowth: 2.2, spdGrowth: 0.2, promotionReqLevel: 25 },

    // --- TIER 2 (SPECIALISTS) ---
    { id: 2101, name: "Knight", tier: 2, resourceType: "RAGE", parentClassId: 1101, focus: "Protection", identity: "The ultimate protector.", growthDesc: "Superior HP (+20) and DEF (+4).", mechanicDesc: "Guardian Aura: +10 DEF to adjacent allies.", leadsTo: "Paladin, Bastion", hpGrowth: 20, mpGrowth: 0, atkGrowth: 3, defGrowth: 4, spdGrowth: 0.2, promotionReqLevel: 50 },
    { id: 2102, name: "Paladin", tier: 2, resourceType: "MANA", parentClassId: 1130, focus: "Holy Tank", identity: "A holy warrior who heals while defending.", growthDesc: "High HP and Magic RES.", mechanicDesc: "Heals lowest HP ally on successful block.", leadsTo: "Saint", hpGrowth: 18, mpGrowth: 10, atkGrowth: 2.5, defGrowth: 3, spdGrowth: 0.2, promotionReqLevel: 50 },
    { id: 2103, name: "Bastion", tier: 2, resourceType: "RAGE", parentClassId: 1117, focus: "Immovable", identity: "A living wall that cannot be moved.", growthDesc: "Highest DEF (+6).", mechanicDesc: "Immune to Knockback; +50% DEF while stationary.", leadsTo: "Fortress", hpGrowth: 22, mpGrowth: 0, atkGrowth: 2, defGrowth: 6, spdGrowth: 0.1, promotionReqLevel: 50 },
    { id: 2104, name: "Berserker", tier: 2, resourceType: "RAGE", parentClassId: 1105, focus: "Missing HP", identity: "A warrior who grows stronger with pain.", growthDesc: "Massive ATK (+6).", mechanicDesc: "+1% ATK for every 1% HP missing.", leadsTo: "Slayer", hpGrowth: 20, mpGrowth: 0, atkGrowth: 6, defGrowth: 0.5, spdGrowth: 0.3, promotionReqLevel: 50 },
    { id: 2105, name: "Champion", tier: 2, resourceType: "RAGE", parentClassId: 1111, focus: "Combos", identity: "Master of close-quarters combat strings.", growthDesc: "High ATK and SPD.", mechanicDesc: "Every 3rd hit deals double damage.", leadsTo: "Warlord", hpGrowth: 16, mpGrowth: 0, atkGrowth: 5, defGrowth: 1.5, spdGrowth: 0.5, promotionReqLevel: 50 },
    { id: 2106, name: "Reaver", tier: 2, resourceType: "RAGE", parentClassId: 1126, focus: "Lifesteal", identity: "A predator who heals from the blood of the weak.", growthDesc: "High ATK and HP.", mechanicDesc: "Heals 20% of DMG dealt to lower HP enemies.", leadsTo: "Death-Knight", hpGrowth: 18, mpGrowth: 0, atkGrowth: 5.5, defGrowth: 1, spdGrowth: 0.4, promotionReqLevel: 50 },
    { id: 2107, name: "Sniper", tier: 2, resourceType: "ENERGY", parentClassId: 1107, focus: "Extreme Range", identity: "A master marksman with unmatched reach.", growthDesc: "Highest Range (+0.5) and ACC.", mechanicDesc: "+2 Range; cannot move and attack in same turn.", leadsTo: "Eagle-Eye", hpGrowth: 10, mpGrowth: 5, atkGrowth: 5, defGrowth: 0.5, spdGrowth: 0.4, promotionReqLevel: 50 },
    { id: 2108, name: "Rogue", tier: 2, resourceType: "ENERGY", parentClassId: 1102, focus: "Stealth DMG", identity: "A shadow who strikes from the unseen.", growthDesc: "High Crit and SPD.", mechanicDesc: "+100% Damage when attacking from STEALTH.", leadsTo: "Assassin", hpGrowth: 12, mpGrowth: 5, atkGrowth: 4, defGrowth: 1, spdGrowth: 0.8, promotionReqLevel: 50 },
    { id: 2109, name: "Grandmaster", tier: 2, resourceType: "ENERGY", parentClassId: 1113, focus: "Momentum", identity: "Martial artist who converts speed into power.", growthDesc: "Highest SPD (+1.0).", mechanicDesc: "DMG scales with tiles moved before attacking.", leadsTo: "Soul-Fist", hpGrowth: 14, mpGrowth: 5, atkGrowth: 4.5, defGrowth: 1, spdGrowth: 1.0, promotionReqLevel: 50 },
    { id: 2110, name: "Saboteur", tier: 2, resourceType: "ENERGY", parentClassId: 1110, focus: "Traps", identity: "Grid specialist who uses explosives.", growthDesc: "High DEX and Tech.", mechanicDesc: "Can place Explosive Traps on empty tiles.", leadsTo: "Engineer", hpGrowth: 13, mpGrowth: 6, atkGrowth: 3.5, defGrowth: 2, spdGrowth: 0.6, promotionReqLevel: 50 },
    { id: 2111, name: "Wizard", tier: 2, resourceType: "MANA", parentClassId: 1103, focus: "AOE Magic", identity: "Master of mass-destruction spells.", growthDesc: "Highest INT (+4).", mechanicDesc: "+1 Spell Range; Spells are 50% larger.", leadsTo: "Archmage", hpGrowth: 8, mpGrowth: 25, atkGrowth: 1, defGrowth: 0.5, spdGrowth: 0.4, promotionReqLevel: 50 },
    { id: 2112, name: "Warlock", tier: 2, resourceType: "MANA", parentClassId: 1109, focus: "Debuff Combo", identity: "Curse weaver who thrives on misery.", growthDesc: "High INT and Mana.", mechanicDesc: "Bonus DMG to enemies with Status Effects.", leadsTo: "Lich", hpGrowth: 10, mpGrowth: 20, atkGrowth: 2, defGrowth: 1, spdGrowth: 0.4, promotionReqLevel: 50 },
    { id: 2113, name: "Druid", tier: 2, resourceType: "MANA", parentClassId: 1112, focus: "Terrain", identity: "Spirit master who shapes the battlefield.", growthDesc: "High MP and Resistance.", mechanicDesc: "Can transform tiles into FOREST or WATER.", leadsTo: "Nature-Avatar", hpGrowth: 12, mpGrowth: 18, atkGrowth: 2.5, defGrowth: 2, spdGrowth: 0.4, promotionReqLevel: 50 },
    { id: 2114, name: "Plague-Doctor", tier: 2, resourceType: "MANA", parentClassId: 1125, focus: "Persistence", identity: "Specialist in long-lasting toxins.", growthDesc: "High INT and Tenacity.", mechanicDesc: "Applied Status Effects last 2 turns longer.", leadsTo: "Alchemist-Lord", hpGrowth: 14, mpGrowth: 15, atkGrowth: 2, defGrowth: 2, spdGrowth: 0.4, promotionReqLevel: 50 },
    { id: 2115, name: "Troubadour", tier: 2, resourceType: "MANA", parentClassId: 1114, focus: "Global Aura", identity: "A singer whose voice reaches everywhere.", growthDesc: "Highest MP (+30).", mechanicDesc: "Auras cover the whole field; 20% weaker.", leadsTo: "Muse", hpGrowth: 12, mpGrowth: 30, atkGrowth: 1.5, defGrowth: 1.5, spdGrowth: 0.5, promotionReqLevel: 50 },
    { id: 2116, name: "Blade-Dancer", tier: 2, resourceType: "ENERGY", parentClassId: 1119, focus: "Evade Stacks", identity: "Graceful combatant who is impossible to hit.", growthDesc: "Superior SPD and Dodge.", mechanicDesc: "Dodge grants a +10% Speed stack (Max 5).", leadsTo: "Wind-Walker", hpGrowth: 10, mpGrowth: 5, atkGrowth: 3.5, defGrowth: 0.5, spdGrowth: 1.2, promotionReqLevel: 50 },
    { id: 2117, name: "Adventurer", tier: 2, resourceType: "ENERGY", parentClassId: 1120, focus: "Versatility", identity: "Master of all tools and weapons.", growthDesc: "High all stats (+2.5).", mechanicDesc: "Can equip any item type without restriction.", leadsTo: "Hero", hpGrowth: 15, mpGrowth: 15, atkGrowth: 2.5, defGrowth: 2.5, spdGrowth: 0.6, promotionReqLevel: 50 },
    { id: 2118, name: "Priest", tier: 2, resourceType: "MANA", parentClassId: 1108, focus: "Purification", identity: "The ultimate beacon of survival.", growthDesc: "High MP and Regen.", mechanicDesc: "Heals also remove all negative statuses.", leadsTo: "Oracle", hpGrowth: 14, mpGrowth: 20, atkGrowth: 1.5, defGrowth: 2, spdGrowth: 0.3, promotionReqLevel: 50 },
    { id: 2119, name: "Monk", tier: 2, resourceType: "ENERGY", parentClassId: 1104, focus: "Mana Shield", identity: "Disciplined fighter who protects with will.", growthDesc: "Superior HP and Tenacity.", mechanicDesc: "Uses Mana to block damage (1 MP = 2 DMG).", leadsTo: "Saint", hpGrowth: 18, mpGrowth: 15, atkGrowth: 3.5, defGrowth: 2.5, spdGrowth: 0.5, promotionReqLevel: 50 }
  ];

  for (const c of classes) {
    await prisma.classTemplate.upsert({
      where: { id: c.id },
      update: c,
      create: c
    });
  }

  console.log("✅ Specialist Class Codex v11.0 Seeded with Tier 2 Evolution.");
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
